[package]
name = "patlite-rs"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dependencies]
rusb = "0.9"
byteorder = "1.4"
clap = { version = "4.5.20", features = ["cargo"] }
tabled = "0.16.0"
